
theme: jekyll-theme-minimal
title: Gunnar Vittrup

![picture](https://drive.google.com/file/d/1ujFIQNcjYkqlZO_A55Q83BvO1_-8ac7_/view?usp=sharing)

description: Bookmark this to keep an eye on my project updates!
